config/routes.rb
Rails.application.routes.draw do
  root "news#home"

  get 'news/home'
  get 'news/new'
  post 'news/create'
  patch 'news/update'
  get 'news/home'
  get 'news/show'
  get 'news/edit'
  get 'news/delete'
  get 'news/update'
  get 'news/show_categories'

  #search
  resources :news do
    collection do
      get 'search'
    end
  end

  #comment
  get "/news/:id", to: "news#show"
  resources :news do resources :comments
  end

  #category create, edit and delete
  resources :categories, only: [:new, :create, :edit, :update, :destroy, :index]

  namespace :admin do
    resources :news do
      member do
        patch 'hide_unhide'  # route to hide/unhide news
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :news
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :news
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :category
  has_many :comments

  validates :title, presence: true
  validates :content, presence: true, length: { minimum: 10 }
  # By default, a new news article will be visible (hidden: false)
  after_initialize :set_defaults, if: :new_record?

  private

  def set_defaults
    self.hidden ||= false
  end
end

app/controllers/admin/news_controller.rb
# app/controllers/admin/news_controller.rb
class Admin::NewsController < ApplicationController
  # Actions for the admin to manage news articles
  before_action :set_news, only: [:show, :edit, :update, :destroy, :hide_unhide]
  def index
    @news = News.order(created_at: :desc)
  end

  def show
    @news = News.find(params[:id])
  end

  def new
    @news = News.new
    @categories = Category.all
  end

  def create
    @news = News.new(news_params)
    if @news.save
      redirect_to admin_news_path(@news)
    else
      @categories = Category.all
      render :new
    end
  end

  def edit
    # Find the news article to edit
    @news = News.find(params[:id])
    @categories = Category.all
  end

  def update
    @news = News.find(params[:id])
    if @news.update(news_params)
      redirect_to admin_news_path(@news)
    else
      render :edit
    end
  end

  def destroy
    @news = News.find(params[:id])
    @news.destroy
    redirect_to admin_news_index_path
  end
  def hide_unhide
    @news.update(hidden: params[:hide] == "true")
    redirect_to admin_news_index_path
  end

  private
  def news_params
    params.require(:news).permit(:title, :content, :category_id, :source)
  end

  def set_news
    @news = News.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  # Display form to create a new category
  def new
    @category = Category.new
  end

  # Create new category
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: "Category created successfully."
    else
      render :new
    end
  end

  # edit an existing category
  def edit
  end

  # Update an existing category
  def update
    if @category.update(category_params)
      redirect_to categories_path, notice: "Category updated successfully."
    else
      render :edit
    end
  end

  # Delete a category
  def destroy
    @category.destroy
    redirect_to categories_path, notice: "Category deleted successfully."
  end

  private
  # Find the category by ID
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create #create a new comment
    @news = News.find(params[:news_id])
    @comment = @news.comments.create(comment_params)
    redirect_to news_path(@news)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  def home
    @news = News.all # search news table and store each row it finds in @news object.
    @news = News.order(created_at: :desc).limit(4) # Orders news by created_at in descending order and limit to 4 news
  end

  def show # The method displays only further details on a single book.
    @news = News.find(params[:id])
  end

  def new # The method lets Rails know that you will create a new object
    @news = News.new
    @categories = Category.all
  end

  def create # The method creates a record into the database
    @news = News.new(news_params)
    if @news.save
      redirect_to action: 'home'
    else
      @categories = Category.all
      render action: 'new'
    end
  end

  def edit # The method looks nearly identical to the show method but EDITABLE
    @news = News.find(params[:id])
    @categories = Category.all
  end

  def update # This method will be called after the edit method and update the changes into the database.
    @news = News.find(params[:id])
    if @news.update(news_params)
      redirect_to action: 'show', id: @news
    else
      @categories = Category.all
      render action: 'edit'
    end
  end


  def destroy # delete a record into the database
    News.find(params[:id]).destroy
    redirect_to action: 'home'
  end

  def news_params
    params.require(:news).permit(:title, :category_id, :source, :content)
  end

  def show_categories
    @categories = Category.includes(:news).order(created_at: :desc) # Preload news for categories
  end

  def search
    if params[:query].present?
      @news = News.where("content LIKE ?", "%#{params[:query]}%").order(created_at: :desc)
    else
      @news = News.order(created_at: :desc)
    end
    render :search # render the search view
  end


end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/admin/news/edit.html.erb
<body>
<div class="sidenav">
  <%= link_to "Admin Home", admin_news_index_path %>
  <%= link_to "Create news", new_admin_news_path %>
  <%= link_to "Logout", news_home_path %>
</div>
<div class="main">
  <h1 class="pageTitle"> Admin - Games News Management System</h1>
  <div align="center">
    <ul id="myUL">
      <h2 id="pageName">Edit a news</h2>
      <!--      create a news-->
      <div class="forms" >
        <%= form_with model: @news, url: admin_news_path(@news), method: :patch do |e| %>
          <p><%= e.label :title %> <%= e.text_field :title %>
          <p><%= e.label :source %> <%= e.text_field :source %>
          <p><%= e.label :category_id %>  <%= collection_select(:news, :category_id, @categories, :id, :name) %>
          <p><%= e.label :content %> <%= e.text_area :content %>
          <p><%= e.submit "Save changes"%>
        <% end %>
        <%= link_to 'Back to admin homepage', admin_news_index_path %>
      </div>
    </ul>
  </div>
</div>

</body>

app/views/admin/news/index.html.erb
<div class="sidenav">
    <%= link_to "Admin Home", admin_news_index_path %>
    <%= link_to "Create news", new_admin_news_path %>
    <%= link_to 'Create New Category', new_category_path %>
    <%= link_to 'Edit and Delete Category', categories_path %>
  <br>
  <%= link_to "Logout", news_home_path %>
</div>
<div class="main">
<h1 class="pageTitle">Admin - Games News Management System</h1>
<div align="center">
<ul id="myUL">
  <h2 id="pageName">All News Articles</h2>
  <% if @news.blank? %>
    <p>No news articles available.</p>
  <% else %>
<!--    Show all news in admin page to perform CRUD operations-->
    <ul id="myUL">
      <% @news.each do |news_item| %>
        <li class="forms">
          <h3 ><%= link_to news_item.title, admin_news_path(news_item) , id: "ind_news_title"%></h3>
          <p class="maxText"><%= news_item.content %></p>
          <div class="crud_btn">
            <%= button_to "Edit", edit_admin_news_path(news_item), method: :get, id: "link_style_button" %>
            <%= button_to "Delete", admin_news_path(news_item), method: :delete, onclick: "confirmDelete(event)" , id: "link_style_button"%>
            <% if news_item.hidden? %>
              <%= button_to "Unhide", hide_unhide_admin_news_path(news_item, hide: false), method: :patch, id: "link_style_button"%>
            <% else %>
              <%= button_to "Hide", hide_unhide_admin_news_path(news_item, hide: true), method: :patch, id: "link_style_button" %>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  <% end %>
</ul>
</div>
</div>

<script>
function confirmDelete(event) {
    if (!confirm("Are you sure you want to delete this item?")) {
        event.preventDefault(); // Prevents the deletion if the user clicks "Cancel"
    }
}
</script>

app/views/admin/news/new.html.erb
<body>
<div class="sidenav">
  <%= link_to "Admin Home", admin_news_index_path %>
  <%= link_to "Create news", new_admin_news_path %>
  <%= link_to "Logout", news_home_path %>
</div>
<div class="main">
  <h1 class="pageTitle">Admin - Games News Management System</h1>
  <div align="center">
    <ul id="myUL">
      <h2 id="pageName">Add a news</h2>
      <div class="forms">
        <%= form_tag :action => 'create' do %>
          <p><label for = "news_title">Title</label> <%= text_field 'news', 'title' %></p>
          <p><label for = "news_source">Source</label> <%= text_field 'news', 'source' %></p>
          <p><label for = "news_subject_id">Category</label> <%= collection_select(:news, :category_id, @categories, :id, :name) %></p>
          <p><label for = "news_content">Content</label><br/> <%= text_area 'news', 'content' %></p>
          <%= submit_tag "Create" %>
        <% end %>
        <br>
        <%= link_to 'Back to admin homepage', admin_news_index_path%>
      </div>
    </ul>
  </div>
</div>
</body>

app/views/admin/news/show.html.erb
<body>
<div class="sidenav">
  <%= link_to "Admin Home", admin_news_index_path %>
  <%#= link_to "News", {:action => 'show_categories'} %>
  <%= link_to "Logout", news_home_path %>
</div>
<div class="main">
  <h1 class="pageTitle">Admin - Games News Management System </h1> <br>
  <div align="center">
    <ul id="myUL">
<!--      show individual news-->
      <h2 id="ind_news_title"><%= @news.title %></h2>
      <div class="article" >
        <p>
          <strong>Source: </strong><%= @news.source %><br />
          <strong>Category: </strong><%= @news.category.name %><br />
          <strong>Date: </strong> <%= @news.created_at %><br />
        <p><%= @news.content %></p>
        </p>
        <hr />
        <br>
      </div>
    </ul>
    <%= link_to 'Back to admin homepage', admin_news_index_path %>
  </div>
</div>
</body>

app/views/categories/edit.html.erb
<div class="sidenav">
  <%= link_to "Admin Home", admin_news_index_path %>
  <%= link_to "Create news", new_admin_news_path %>
  <%= link_to 'Create New Category', new_category_path %>
  <%= link_to 'Edit and Delete Category', categories_path %>
</div>
<h1 class="title">Edit Category</h1>
<div class="main">
  <div align="center">
<ul id="myUL">
<%= form_with model: @category, local: true do |form| %>
  <li>
    <%= form.label :name , id: 'link_style_button'%><br>
    <%= form.text_field :name %>
  </li>

  <p>
    <%= form.submit "Update Category" %>
  </p>
<% end %>
</ul>
<%= link_to 'Back to Admin', admin_news_index_path %>
  </div>
</div>

app/views/categories/index.html.erb
<h1 class="title">Categories</h1>
<div class="sidenav">
  <%= link_to "Admin Home", admin_news_index_path %>
  <%= link_to "Create news", new_admin_news_path %>
  <%= link_to 'Create New Category', new_category_path %>
  <%= link_to 'Edit and Delete Category', categories_path %>
</div>

<div class="main">
<ul id="myUL">
<!--  Show list of categories-->
  <% @categories.each do |category| %>
    <li>
      <h2 id="h2_news_title"> <%= category.name %>
        <%= button_to "Edit", edit_category_path(category), method: :get, class: "action-button" , id: 'link_style_button'%>
        <%= button_to 'Delete', category_path(category), method: :delete, onclick: "confirmDelete(event)" , id: 'link_style_button'%> </h2>
    </li>
  <% end %>
</ul>

<%= link_to 'Back to Home', admin_news_index_path %>
</div>
<script> // Prevents the deletion if the user clicks "Cancel"
function confirmDelete(event) {
if (!confirm("Are you sure you want to delete this item?")) {
event.preventDefault();
}
}
</script>

app/views/categories/new.html.erb
<div class="sidenav">
  <%= link_to "Admin Home", admin_news_index_path %>
  <%= link_to "Create news", new_admin_news_path %>
  <%= link_to 'Edit and Delete Category', categories_path %>
</div>

<div class="main">
<h1 class="pageTitle">Admin - Games News Management System</h1>

<h2 id="pageName">Create a New Category</h2>
<ul id="myUL">

  <div class="forms">
<%= form_with model: @category, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit "Create Category" %>
  </p>
<% end %>
  </div>
</ul>
<%= link_to 'Back to Admin', admin_news_index_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for(:title) || "News Management App Alessandro" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <link rel="manifest" href="/manifest.json">
  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag "style", media: "all" %>


  <%= javascript_importmap_tags %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/news/home.html.erb
<body>
<div class="sidenav">
  <%= link_to "Home", {:action => 'home'} %>
  <%= link_to "News", {:action => 'show_categories'} %>
  <%= link_to "Categories", news_show_categories_path  %>
  <%= link_to "Admin", admin_news_index_path %>
</div>
<div class="main">
  <h1 class="pageTitle">Games News</h1>
  <div align="center">
    <div align="center" id="form_search">
      <%= form_tag search_news_index_path, method: :get do %>
        <input type="text" name="query" id="myInput" placeholder="Search for news..." value="<%= params[:query] %>" >
        <%= submit_tag "Search" %>
      <% end %>
    </div>
    <ul id="myUL">
      <h2 id="pageName">Latest News</h2>
      <br>
      <!-- Display Title and news content -->
      <% if @news.blank? %>
        <p>There are not any news currently in the system.</p>
      <% else %>
        <ul id="news-list">
<!--          show only news that are not hidden-->
          <% @news.where(hidden: false).each do |news| %>
            <li class="news_list" >
              <h2 id="h2_news_title"><%= link_to news.title , {:action => 'show', :id => news.id} %></h2>
              <p class="maxText"><%= news.content %></p>
              <%= link_to "Read More", {:action => 'show', :id => news.id} %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </ul>
  </div>
</div>
</body>

app/views/news/new.html.erb
<body>
<div class="sidenav">
  <%= link_to "Home", {:action => 'home'} %>
  <%= link_to "News", {:action => 'show_categories'} %>
  <%= link_to "Admin", admin_news_index_path %>
</div>
<div class="main">
  <h1 class="title">Games News Management System</h1>
  <div align="center">
    <ul id="myUL">
      <h2 id="pageName">Add a news</h2>
      <div class="" >
        Form to create a news
        <%= form_tag :action => 'create' do %>
          <p><label for = "news_title">Title</label> <%= text_field 'news', 'title' %></p>
          <p><label for = "news_source">Source</label> <%= text_field 'news', 'source' %></p>
          <p><label for = "news_subject_id">Category</label> <%= collection_select(:news, :category_id, @categories, :id, :name) %></p>
          <p><label for = "news_content">Content</label><br/> <%= text_area 'news', 'content' %></p>
          <%= submit_tag "Create" %>
        <% end %>
        <%= link_to 'Back', {:action => 'home'} %>
      </div>

    </ul>
  </div>
</div>

</body>


app/views/news/search.html.erb
<div class="sidenav">
  <%= link_to "Home", {:action => 'home'} %>
  <%= link_to "News", {:action => 'show_categories'} %>
  <%= link_to "Admin", admin_news_index_path %>
</div>
<div class="main">

  <h1 class="pageTitle">Games News</h1>

  <ul id="myUL">
    <h2 class="title">Search Results for "<%= params[:query] %>"</h2>
    <% if @news.blank? %>
      <p>No news articles matched your search query.</p>
    <% else %>
      <!-- show  news if searched word match-->
      <% @news.where(hidden: false).each do |news_item| %>
        <li class="article">
          <h3 id="h3_show_cat"><%= news_item.title %></h3>
          <p class="maxText"><%= news_item.content%></p>
          <p><%= link_to "Read More", {:action => 'show', :id => news_item.id} %></p>
        </li>
      <% end %>
    <% end %>
    <br>
    <%= link_to 'Back to homepage', news_home_path %>
  </ul>
</div>

app/views/news/show.html.erb
  <body>
  <div class="sidenav">
    <%= link_to "Home", {:action => 'home'} %>
    <%= link_to "News", {:action => 'show_categories'} %>
    <%= link_to "Admin", admin_news_index_path %>
  </div>
  <div class="main">
    <h1 class="pageTitle">Games News </h1> <br>
    <div align="center">
      <ul id="myUL">
        <!-- SHow individual news-->
        <h2 id="ind_news_title"><%= @news.title %></h2>
        <div class="forms" >
          <div class="comment_align">
          <p>
            <strong>Source: </strong><%= @news.source %><br />
            <strong>Category: </strong><%= @news.category.name %><br />
            <strong>Date: </strong> <%= @news.created_at %><br />
            <p><%= @news.content %></p>
          </p>
          </div>
          <hr />
          <br>
          <!-- insert a Comment-->
          <div class="comment_align">
          <h2 id="pageName">Comments</h2>
          <% @news.comments.each do |comment| %>
            <p > <strong>Name:</strong> <%= comment.commenter %> </p>
            <p> <strong>Comment:</strong> <%= comment.body %> </p>
              <br>
          <% end %>
          </div>
          <h3 id="h3_show_cat">Add a comment:</h3>
          <%= form_with model: [ @news, @news.comments.build ] do |form| %>
            <p> <%= form.label :commenter %><br> <%= form.text_field :commenter %> </p>
            <p> <%= form.label :body %><br> <%= form.text_area :body %> </p> <p> <%= form.submit %> </p>
          <% end %>
          <br>
          <%= link_to 'Back to homepage', news_home_path %>
        </div>

      </ul>
    </div>
  </div>

  </body>

app/views/news/show_categories.html.erb
<body>
<!-- side bar and menu  -->
<div class="sidenav">
  <%= link_to "Home", {:action => 'home'} %>
  <%= link_to "News", {:action => 'show_categories'} %>
  <%= link_to "Admin", admin_news_index_path %>
</div>
<div class="main">
  <h1 class="pageTitle">Games News</h1>
  <div align="center">
    <div align="center" id="form_search">
      <%= form_tag search_news_index_path, method: :get do %>
        <input type="text" name="query" id="myInput" placeholder="Search for news..." value="<%= params[:query] %>">
        <%= submit_tag "Search" %>
      <% end %>
    </div>
    <ul id="myUL">
      <h2 id="pageName">News Categories</h2>
      <!-- Display Categories and news of each category -->
      <% if @categories.blank? %>
        <p>There are not any news currently in the system.</p>
      <% else %>
        <ul id="news-list">
          <% @categories.each do |category| %>
              <h2><%= category.name %></h2>
              <% if category.news.any? %>
              <!--   show only news that are not hidden-->
                <% category.news.where(hidden: false).each do |news| %>
                  <li class="news_list" >
                    <h3 id="h3_show_cat"><%= link_to news.title, {:action => 'show', :id => news.id} %></h3>
                    <p class="maxText"><%= news.content %></p>
                    <p><%= link_to "Read More", {:action => 'show', :id => news.id} %></p>
                  </li>
              <% end %>
                <br>
              <% end %>
          <% end %>
        </ul>
      <% end %>

    </ul>
  </div>
</div>

</body>